# Generated by Django 3.2.23 on 2024-01-27 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240125_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер вводится в формате: '+99999999999'.", regex='^\\+?1?\\d{9,11}$')])),
                ('contact', models.CharField(max_length=100)),
                ('memo', models.TextField(max_length=400)),
            ],
        ),
    ]
