# Generated by Django 3.2.23 on 2024-02-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
