# Generated by Django 3.2.23 on 2024-01-25 15:45

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(upload_to='portfolio/about/'),
        ),
    ]
