# Generated by Django 3.2.23 on 2024-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_mail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='memo',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='mail',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
